services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
    volumes:
      - ${PROJECT_DIR}:${PROJECT_DIR}
    working_dir: ${PROJECT_DIR}
    networks:
      - postgres-docker_local-network
    env_file:
      - .env.test
    #command: sh -c "./wait-for-it.sh postgres:5432 -- python scripts/bootstrap_db.py && pytest"
    command: sh -c "./wait-for-it.sh postgres:5432 -- pytest"

networks:
     postgres-docker_local-network:
       external: true
