services:
  fastapi:
    build: .
    volumes:
      - ${PROJECT_DIR}:${PROJECT_DIR}
    working_dir: ${PROJECT_DIR}
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - postgres-docker_local-network

networks:
     postgres-docker_local-network:
       external: true