name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest httpx

    - name: Set up environment variables
      run: |
        echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

    - name: Run tests
      run: |
        pytest -v tests/

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test-results
        path: pytest-results.xml

    - name: Report test coverage
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true