name: Run Tests

on:
  push:
    branches:
      - main
      - fix-force-4o-mini-bug
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: List installed packages
      run: pip list

    - name: Show current directory structure
      run: ls -R

    - name: Show content of test file
      run: cat tests/test_youtube_utils.py

    - name: Show content of main file
      run: cat youtube_utils.py

    - name: Run tests with maximum verbosity
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: |
        echo "Current working directory: $(pwd)"
        echo "PYTHONPATH: $PYTHONPATH"
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest tests/ -vv --capture=no --tb=long