name: Run Tests

on: [push, pull_request]

env:
  NODE_VERSION: 20

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v20
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v20
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Set up Python
      uses: actions/setup-python@v20
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    - name: Run tests
      run: pytest